In [1]:
import pandas as pd

In [15]:
df = pd.read_csv("./featureselection.csv")

In [16]:
df['System'] = df["System"] / 6.6842*10
df['Station'] = df['Station'] / 6.3176*10

In [17]:
df['Feat'].value_counts()

near_hospitality         10
parking                   8
30net_medical             6
near_university           6
near_entertainment        5
near_pop_old              5
15net_hunits_attached     5
15net_hunits_old          5
15net_university          4
near_emp_pay              4
15net_hunits_medium       4
30net_hunits_large        4
near_employment           4
near_hunits_owner         3
near_medical              3
15net_hospitality         3
near_hunits_attached      3
30net_hunits_medium       2
near_labor_force          2
near_population           2
near_family               2
near_business             2
near_hunits_detached      2
15net_hunits_vacant       2
near_hunits_large         2
30net_hospitality         2
15net_medical             2
near_hunits_new           2
30net_entertainment       2
15net_employed            2
near_pop_rich             1
30net_emp_pay             1
15net_pop_child           1
15net_emp_pay             1
30net_hunits_vacant       1
30net_university          1
near_finance              1
near_house_w_child        1
15net_bachelors           1
15net_household           1
near_pop_poor             1
15net_entertainment       1
30net_hunits_old          1
near_hunits_old           1
30net_population          1
near_pop_child            1
near_foreign_born         1
30net_hunits_detached     1
Name: Feat, dtype: int64

In [18]:
df.groupby('Feat')[['System', 'Station']].sum()

                          System    Station
Feat
15net_bachelors         0.000000   0.000000
15net_emp_pay           0.000000   0.000000
15net_employed          1.478861   1.582880
15net_entertainment     1.496065   1.489015
15net_hospitality       1.606924   1.603774
15net_household         0.000000   0.000000
15net_hunits_attached   2.807217   3.047676
15net_hunits_medium     2.072051   2.074522
15net_hunits_old        4.953024   4.853584
15net_hunits_vacant     1.200293   1.443903
15net_medical           1.349451   1.264088
15net_pop_child         1.436821   1.275168
15net_university        5.017504   5.001425
30net_emp_pay           1.436821   1.275168
30net_entertainment     2.845516   2.753102
30net_hospitality       1.200293   1.443903
30net_hunits_detached   0.735167   0.973154
30net_hunits_large      3.521439   3.512410
30net_hunits_medium     0.735167   0.973154
30net_hunits_old        1.431585   1.341174
30net_hunits_vacant     0.000000   0.000000
30net_medical           5.123126   5.182189
30net_population        1.478861   1.582880
30net_university        1.496065   1.489015
near_business           1.349451   1.264088
near_emp_pay            3.102989   3.092788
near_employment         2.696359   2.932918
near_entertainment      4.133180   4.208085
near_family             2.845516   2.753102
near_finance            1.496065   1.489015
near_foreign_born       1.436821   1.275168
near_hospitality       10.000000  10.000000
near_house_w_child      1.496065   1.489015
near_hunits_attached    1.413034   1.752723
near_hunits_detached    2.786272   2.539255
near_hunits_large       2.932887   2.764183
near_hunits_new         2.171988   2.248322
near_hunits_old         1.496065   1.489015
near_hunits_owner       2.214027   2.556034
near_labor_force        0.735167   0.973154
near_medical            3.516202   3.578416
near_pop_child          1.496065   1.489015
near_pop_old            4.853086   4.679783
near_pop_poor           1.436821   1.275168
near_pop_rich           0.000000   0.000000
near_population         2.845516   2.753102
near_university         5.588253   5.652938
parking                 7.084318   7.141953